### ISSUE TITLE
老师名字都被你写错了😓

### ISSUE THREAD

**Issue by fangwentong** [traitorousfc/HIT-OSLab#1]
网易云课堂的操作系统课程被拆分成四门， 课程资源建议改为 [李治军老师的云课堂主页](http://mooc.study.163.com/u/3793984885#/c)， 或者将四门课链接都附上

**Comment by fangwentong** [comment]
最近我也在看这门课程， 感叹当初本末倒置， 课下花时间太少.

**Comment by traitorousfc** [comment]
Okay, roger that.
